words = [
    "agentic",
    "bunx",
    "cie",
    "consensia",
    "decentralizedly",
    "enneagram",
    "excalidraw",
    "frontmatter",
    "frontmatters",
    "hesperi",
    "hesprs",
    "hēsperus",
    "implemental",
    "inarguably",
    "ipynb",
    "lgbtqia",
    "libertas",
    "lifecycles",
    "lovership",
    "loverships",
    "mbti",
    "microkernel",
    "omnikernel",
    "opensource",
    "orchestratable",
    "oxfmt",
    "oxlint",
    "pnpm",
    "pnpx",
    "pointeract",
    "preact",
    "preconnecting",
    "prerender",
    "prerendered",
    "prerendering",
    "programmatically",
    "rgba",
    "shadcn",
    "subfolders",
    "synthkernel",
    "tauri",
    "techstack",
    "techstacks",
    "trito",
    "turborepo",
    "unmaintainability",
    "vite",
    "vitepress",
]
