words = [
    "CLI",
    "DFS",
    "DOI",
    "LLM",
    "Nextcloud",
    "OOP",
    "OSAP",
    "Reusability",
    "Yandex",
    "agentic",
    "backpressure",
    "breakpoint",
    "bunx",
    "cie",
    "ciphertext",
    "consensia",
    "dav",
    "decentralizedly",
    "decrypter",
    "enneagram",
    "excalidraw",
    "explainers",
    "frontmatter",
    "frontmatters",
    "gpt",
    "hesperi",
    "hesprs",
    "hēsperus",
    "hkdf",
    "hēsperus",
    "idb",
    "implemental",
    "inarguably",
    "ipynb",
    "irreproducible",
    "lgbtqia",
    "libertas",
    "lifecycle",
    "lifecycles",
    "localspace",
    "lovership",
    "loverships",
    "mbti",
    "microkernel",
    "microtask",
    "mkdir",
    "natively",
    "ocid",
    "omnikernel",
    "openai",
    "opensource",
    "orchestratable",
    "oxfmt",
    "oxlint",
    "pnpm",
    "pnpx",
    "pointeract",
    "preact",
    "preconnecting",
    "prerender",
    "prerendered",
    "prerendering",
    "profiler",
    "programmatically",
    "progressivist",
    "rclone",
    "reactively",
    "rgba",
    "scaffolder",
    "shadcn",
    "siv",
    "socio",
    "subfolders",
    "synthkernel",
    "tauri",
    "techstack",
    "techstacks",
    "trito",
    "turborepo",
    "unbundle",
    "underspecified",
    "unmaintainability",
    "vite",
    "vitepress",
    "vitest",
    "webdav",
    "whistleblower",
]
